services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:8081"  # 修正為映射容器的 8081 埠
    volumes:
      - ./frontend:/usr/src/app           # 工作目錄挂载到容器中
      - /usr/src/app/node_modules         # 防止 node_modules 被覆盖
    networks:
      - moodle-network
    env_file: ".env"                      # 使用環境變數文件

  nginx:
    build: ./nginx                        # 添加 Nginx 配置，提供反向代理
    links:
      - frontend:frontend                 # 與前端容器連接
    ports:
      - "80:80"                           # 將 Nginx 的 80 埠映射到主機的 80 埠
    networks:
      - moodle-network

  backend:
    build: ./moodle-backend               # 後端的 Dockerfile 位於 moodle-backend 文件夾
    ports:
      - "8080:80"                         # 對外暴露 8080 端口
    volumes:
      - moodle_app:/var/www/html/moodle         # 使用命名卷持久化 Moodle 應用數據
      - ./apache2.conf:/etc/apache2/apache2.conf # Apache 配置文件
      - moodle-data:/var/moodledata             # Moodle 數據目錄持久化
    depends_on:
      - db
    networks:
      - moodle-network
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle_db
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: yourpassword
      MOODLE_URL: http://localhost:8080

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./moodle-db-backup:/docker-entrypoint-initdb.d  # 初始 SQL 腳本
      - db_data:/var/lib/mysql                          # 數據持久化
    networks:
      - moodle-network

  flask-txt:                               # 保留 Flask 應用服務
    build:
      context: ./flask-txt                 # Flask Dockerfile
    ports:
      - "5000:5000"                        # Flask 端口映射
    volumes:
      - ./data:/data                       # 持久化資料夾
    networks:
      - moodle-network                     # 與現有服務保持同一網路
  
  phpmyadmin:  # 新增的 phpMyAdmin 服務（添加在 db 下方，屬於 services 區塊）
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword  # 必須與 db 服務的 root 密碼一致
    ports:
      - "8081:80"  # 映射本機的 8081 埠到 phpMyAdmin 的 80 埠
    depends_on:
      - db
    networks:
      - moodle-network

networks:
  moodle-network:

volumes:
  db_data:
  moodle-data:
  moodle_app:
