services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # 修正為映射容器的 3000 埠
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - moodle-network
    env_file: ".env"

  nginx:
    build: ./nginx
    links:
      - frontend:frontend
    ports:
      - "8088:80"
    networks:
      - moodle-network

  backend:
    build: ./moodle-backend
    ports:
      - "8080:80"
    volumes:
      # - moodle_app:/var/www/html/moodle
      - ./moodle-backend:/var/www/html/moodle
      - ./apache2.conf:/etc/apache2/apache2.conf
      - moodle-data:/var/moodledata
    depends_on:
      - db
    networks:
      - moodle-network
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle_db
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: yourpassword
      MOODLE_URL: https://eduai-api.andy-lu.dev

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./moodle-db-backup:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - moodle-network

  flask-txt:
    build:
      context: ./flask-txt
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    networks:
      - moodle-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - moodle-network

  audio:
    build:
      context: ./audio
    ports:
      - "5001:5000"
    volumes:
      - ./audio/temp:/tmp
    networks:
      - moodle-network
    depends_on:
      - db
      - backend

networks:
  moodle-network:

volumes:
  db_data:
  moodle-data:
  # moodle_app:
