services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - moodle-network

  backend:
    build: ./moodle-backend
    ports:
      - "8080:80"
    volumes:
      - moodle_app:/var/www/html/moodle
      - ./apache2.conf:/etc/apache2/apache2.conf
      - moodle-data:/var/moodledata
    depends_on:
      - db
    networks:
      - moodle-network
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle_db
      MOODLE_DB_USER: moodleuser
      MOODLE_DB_PASSWORD: yourpassword
      MOODLE_URL: http://localhost:8080

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle_db
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./moodle-db-backup:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - moodle-network

  flask-txt:
    build:
      context: ./flask-txt  # Flask 應用程式的 Dockerfile 位於 flask-txt 文件夾
    ports:
      - "5000:5000"         # 映射 Flask 的 5000 端口
    volumes:
      - ./data:/data        # 持久化文字檔的資料夾
    networks:
      - moodle-network      # 與現有服務保持同一網路

networks:
  moodle-network:

volumes:
  db_data:
  moodle-data:
  moodle_app:
